argocd-apps:
  applications:
    rllopsite:
      namespace: argo-cd
      project: default
      source:
        repoURL: https://github.com/ricardllop/oke-helm-charts.git
        targetRevision: HEAD
        path: rllopsite-chart
      destination:
        server: https://kubernetes.default.svc
        namespace: rllopsite
      syncPolicy:
        automated:
          prune: true
          selfHeal: true